### ISSUE TITLE
Github Actions not passing

### ISSUE THREAD

**Issue by Robin-Van-de-Merghel** [DIRACGrid/Pilot#244]
In this repository, `integration.yml` workflows aren't working at all. See [here](https://github.com/DIRACGrid/Pilot/actions/workflows/integration.yml), none of them are passing.

This issue may comes from a misconfiguration in the `secrets` data. In effect, @fstagni ['s `integration.yml` workflows](https://github.com/fstagni/Pilot/actions/workflows/integration.yml) work well. The only input difference between these two repositories could be secrets:

```yml
env:
          HOSTCERT_BASE64: ${{ secrets.HOSTCERT_BASE64 }}
          HOSTKEY_BASE64: ${{ secrets.HOSTKEY_BASE64 }}
```

I guess by adding secrets to the Actions, it could work.
